### PR TITLE
Biniyam dev

### PR DESCRIPTION
**Pull request by benbel376**
-  Metadata has been generated
-  A couple of data cleaning functions have been added to the data_cleaning.py script (generate_metadata, channel_count, make_stereo)
-  Mono files have been converted to Stereo

### CODE REVIEW

**Comment by Micky373** [comment]
Hello @benbel376,

You have done a great work 💯 💯 💯 .
I have just only these two comments:

- [ ] Please if you can modularize this loop as a method in your script so that our code will be reusable

image

- [ ] Please on these two places on our value counts try to comment that we have taken only 1000 sound samples for our case so that in the future we can take all of them. Since you are showing 1 for 1000 and 400 for 9875 it is somehow ambigous. So we can comment here that our train dataset contains only 1000 sounds and those are the cleaned ones for the time being.

image
image


Apart from that it is well structured and perfect code 👍🏽 👍🏽 👍🏽 

Thanks!!!!

**Review by Micky373 — CHANGES_REQUESTED** [review]
Hello @benbel376 ,

You have done awesome work. 👍🏽 👍🏽 
I have added some comments above please check them and act accordingly.

Thanks!!!

**Review by abeselomg — CHANGES_REQUESTED** [review]
Hey @benbel376 great job. I think one minor change should be applied apart from @Micky373 comments. Maybe we can modularize the logger into a class and use it in our scripts.

Apart from that, great job! 
P.S. I can share a ready-made script about loggers .

**Review by Micky373 — APPROVED** [review]

**Review by meriab21 — APPROVED** [review]
Nice work!

**Pull request merged**
